/**
 * Script to delete only specific seed/placeholder projects from Sanity dataset.
 * Leaves custom user-created projects untouched.
 *
 * Usage: npx tsx scripts/delete-projects.ts
 */

try {
  process.loadEnvFile(".env.local");
} catch {
  // fall through
}

import { createClient } from "@sanity/client";

const projectId = process.env.NEXT_PUBLIC_SANITY_PROJECT_ID;
const dataset = process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production";
const token = process.env.SANITY_API_WRITE_TOKEN;

if (!projectId || !token) {
  console.error("Missing NEXT_PUBLIC_SANITY_PROJECT_ID or SANITY_API_WRITE_TOKEN in .env.local.");
  process.exit(1);
}

const client = createClient({
  projectId,
  dataset,
  apiVersion: "2024-01-01",
  token,
  useCdn: false,
});

// List of placeholder project document IDs generated by seed-sanity script
const PLACEHOLDER_PROJECT_IDS = [
  "project-residence-at-kasaragod",
  "project-luxury-residence-at-mukkom",
  "project-contemporary-minimalist-interior",
  "project-private-residence-construction",
  "project-commercial-interior-fit-out",
  "project-institutional-campus-building",
];

async function deletePlaceholderProjectsOnly() {
  console.log("Deleting only seed placeholder projects from Sanity...");

  const transaction = client.transaction();
  for (const id of PLACEHOLDER_PROJECT_IDS) {
    transaction.delete(id);
    transaction.delete(`drafts.${id}`);
  }

  await transaction.commit();
  console.log("Placeholder projects successfully removed. Custom projects remain untouched!");
}

deletePlaceholderProjectsOnly().catch((err) => {
  console.error("Deletion failed:", err);
  process.exit(1);
});
